### ISSUE TITLE
Problem with adding the plugin to build.gradle

### ISSUE THREAD

**Issue by tienthai0205** [dstukalov/VideoConverter#4]
I tried to add the library to my build.gradle but got this error:
Unresolved dependency: com.dstukalov:videoconverter:1.8Java(0)

**Comment by dstukalov** [comment]
the library is hosted on JCenter, please make sure you have `jcenter()` in the list of repositories in your top-level `build.gradle` file:
```
repositories {
    jcenter()
}

**Comment by tienthai0205** [comment]
Thank you, the error goes away now. But i still couldn't seem to use  
`import com.dstukalov.videoconverter.MediaConverter;` (the package is not recognized).  Do you have any idea what could be the problem?

**Comment by dstukalov** [comment]
you need to add library to build.gradle
