### ISSUE TITLE
hevc mp4 format issue

### ISSUE THREAD

**Issue by firear** [dstukalov/VideoConverter#7]
I got this issue when I use hevc and StreamingMuxer, but no errors on hevc and AndroidMuxer.

ffprobe test1.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5623fdb6c700] stream 1, contradictionary STSC and STCO
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5623fdb6c700] error reading header

=================
ffprobe test2.mp4 
[hevc @ 0x5569d8ff7f80] VPS 0 does not exist
[hevc @ 0x5569d8ff7f80] SPS 0 does not exist.
[hevc @ 0x5569d8ff7f80] PPS id out of range: 0
[hevc @ 0x5569d8ff7f80] Error parsing NAL unit #0.
[hevc @ 0x5569d8ff7f80] PPS id out of range: 0

**Comment by dstukalov** [comment]
Would it be possible to attach an original video?

**Comment by firear** [comment]
[vide.zip](https://github.com/dstukalov/VideoConverter/files/8471274/vide.zip)


> Would it be possible to attach an original video?

**Comment by dstukalov** [comment]
fixed in https://github.com/dstukalov/VideoConverter/commit/25d29d4eb79a9f39f21807478826b21b3bd234b6

**Comment by firear** [comment]
> fixed in [25d29d4](https://github.com/dstukalov/VideoConverter/commit/25d29d4eb79a9f39f21807478826b21b3bd234b6)

thanks!
there is still another issue here.
ffprobe test1.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5623fdb6c700] stream 1, contradictionary STSC and STCO
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5623fdb6c700] error reading header
this file size is too big to upload here(4G+)

**Comment by dstukalov** [comment]
fixed in https://github.com/dstukalov/VideoConverter/commit/9d414b7bc720396cbeab693c33c00a40620b47dd

**Comment by firear** [comment]
tested.still report the error.
contradictionary STSC and STCO

**Comment by dstukalov** [comment]
Is 4GB+ original file or the output. If output is relatively small would it be possible to attach it here?

**Comment by firear** [comment]
<img width="1198" alt="截屏2022-04-17 08 29 45" src="https://user-images.githubusercontent.com/1518830/163695346-ec61d792-cc52-402f-b76a-9ddfbd03b383.png">

```c
if (sc->stsc_count && sc->stsc_data[ sc->stsc_count - 1 ].first > sc->chunk_count) {
        av_log(c->fc, AV_LOG_ERROR, "stream %d, contradictionary STSC and STCO\n",
               st->index);
        return AVERROR_INVALIDDATA;
    }
```

**Comment by dstukalov** [comment]
it is possible https://github.com/dstukalov/VideoConverter/commit/709a2f6f97316fe7e8266fc6005e7324ed020c7d fixes "contradictionary STSC and STCO" issue on some files, please try

**Comment by firear** [comment]
thanks 😊 it's fixed!
